local_addr: "0.0.0.0:0"  # Local address to bind to
sip:
  user: "SIPUSER"         # SIP username
  password: "SIPPASSWORD" # SIP password 
  host: "SIPHOST"         # SIP server hostname
  port: 5060              # SIP server port
spam:
  blacklist_paths:      # Paths to blacklist files/directories
    - "./blacklist.txt"
    - "./blacklists/"
  sleep_seconds: 1      # Seconds to wait before hanging up spam calls
  use_inotify: true    # Watch blacklist files for changes
